---
title: "Lab 5"
output: html_notebook
---

Task 1

```{r}
fb <- function(n) {
  if (n == 1 || n == 2) {
    return(1)
  } else {
      return(fb(n - 1) + fb(n - 2))
    }
}

fb(8)
```

Task 2

```{r}
det <- function(A, i){
  
  if ((dim(A)[1] == 1) && (dim(A)[2] == 1)){
    return (A[1, 1])
  }
  
  if ((dim(A)[1]) == 2 && (dim(A)[2] == 2)){
    return (A[1, 1] * A[2,2] - A[1, 2] * A[2,1])
  }
  
  else{
    s = 0
    
    for (j in 1:dim(A)[2]){
      s = s + ((-1) ^ (i + j)) * A[i, j] * det(A[-i, -j], i)
    }
  }
  
  return (s)
  
}
```

Task 3a

```{r}
# Set the mean and covariance matrix for the bivariate normal distribution
mean_vec <- c(0, 0)
cov_matrix <- matrix(c(1, 0.7, 0.7, 1), nrow = 2)
```

```{r}
# Generate the first data set with 20 pairs of (x, y)
data_set_1 <- rmvnorm(20, mean = mean_vec, sigma = cov_matrix)

# Add the additional point (10, 10) to create the second data set
data_set_2 <- rbind(data_set_1, c(10, 10))

# Add the additional point (10, -0.3) to create the third data set
data_set_3 <- rbind(data_set_1, c(10, -0.3))
```

```{r}
# Separate the data sets into variables
x1 <- data_set_1[, 1]
y1 <- data_set_1[, 2]

x2 <- data_set_2[, 1]
y2 <- data_set_2[, 2]

x3 <- data_set_3[, 1]
y3 <- data_set_3[, 2]
```

Task 3b

```{r}
# Fit simple linear regression models to each data set
model1 <- lm(y1 ~ x1, data = data.frame(x1, y1), x=TRUE)
model2 <- lm(y2 ~ x2, data = data.frame(x2, y2), x=TRUE)
model3 <- lm(y3 ~ x3, data = data.frame(x3, y3), x=TRUE)
```

Task 3c

```{r}
histhat <- function(model) {
  # Calculate leverage values
  leverage <- model$x %*% solve(t(model$x) %*% model$x) %*% t(model$x)
  
  # Print heading with model formula
  formula_str <- deparse(model$call$formula)
  writeLines(paste("Model Formula:", formula_str))
  
  # Print leverage values
  writeLines(noquote(paste("Leverage Values:", leverage)))
  
  # Generate and display histogram
  hist(leverage, main = "Leverage Values Histogram", xlab = "Leverage", ylab = "Frequency")
}
```

Task 3d

```{r}
# Call the function for each model
histhat(model1)
```

```{r}
histhat(model2)
```

```{r}
histhat(model3)
```
