---
title: "Lab 7"
output: html_notebook
---

Task 1a

```{r}
data(teengamb)
```

```{r}
fullmodel <- lm(gamble ~ ., data = teengamb)
nullmodel <- lm(gamble ~ 1, data = teengamb)
```

```{r}
drop1(fullmodel, scope~., test = "F")
```

```{r}
model2 <- lm(gamble ~ sex + income + verbal, data = teengamb)
drop1(model2, scope~., test = "F")
```

```{r}
model3 <- lm(gamble ~ sex + income, data = teengamb)
drop1(model3, scope~., test = "F")
```

Task 1b

```{r}
add1(nullmodel, scope~. + sex + status + income + verbal, test = "F")
```

```{r}
model2 <- lm(gamble ~ income, data = teengamb)
add1(model2, scope~. + sex + status + verbal, test = "F")
```

```{r}
model3 <- lm(gamble ~ income + sex, data = teengamb)
add1(model3, scope~. + status + verbal, test = "F")
```

Task 1c

```{r}
step(nullmodel, scope = ~. + sex + status + income + verbal)
```

Task 2a

```{r}
data(trees)
?trees
pairs(trees)
```

```{r}
y <- matrix(trees$Volume, 31, 1)
X <- matrix(cbind(rep(1, 31), trees$Girth, trees$Height), 31, 3)
```

```{r}
y
X
```

```{r}
(b <- solve(t(X)%*%X, t(X)%*%y))
```

```{r}
SSTotal <- t(y)%*%y
SSRes <- sum((y - X%*%b)^2)
SSReg <- SSTotal - SSRes
```

```{r}
X2 <- X[, -3]
X2
```

```{r}
Rb2 <- t(y)%*%X2%*%solve(t(X2)%*%X2)%*%t(X2)%*%y
Rb1b2 <- SSReg - Rb2
```

```{r}
Fstat <- (Rb1b2/1)/(SSRes/(31-3))
pf(Fstat, 1, 31-3, lower.tail = FALSE)
```

```{r}
model <- lm(Volume ~ Girth + Height, data = trees)
null <- lm(Volume ~ Girth, data = trees)

anova(null, model)
```
