---
title: "Lab 3"
output: html_notebook
---

Task 1

```{r}
if (x <= 0){
  y = -(x^3)
} else if (x > 1){
  y = sqrt(x)
} else {
  y = x^2
}

```

```{r}
# input
x.values <- seq(-2, 2, by = 0.1)

# for each x calculate y
n <- length(x.values)
y.values <- rep(0, n)

for (i in 1:n) {
  x <- x.values[i]

  if (x <= 0){
    y = -(x^3)
  } else if (x > 1){
    y = sqrt(x)
  } else {
    y = x^2
  }

  y.values[i] <- y
}

# output
plot(x.values, y.values, type = "l")
```

Task 2

```{r}
h = function(x, n){
  val = 0.0
  
  for (i in 0:n){
    val = val + (x^i)
  }
  
  return (val)
}
```

Task 3

```{r}
geom = function(x, n){
  val = (1-(x^(n+1))) / (1-x)
  
  return (val)
}
```

```{r}
#Compute using for loop

h(0.3, 55)
h(6.6, 8)
```

```{r}
#Compute using geometric sum

geom(0.3, 55)
geom(6.6, 8)
```

Task 4

```{r}
h_while = function(x, n){
  val = 0.0
  i = 0
  
  while(i <= n){
    val = val + (x^i)
    i = i + 1
  }
  
  return (val)
}
```

```{r}
h_while(0.3, 55)
h_while(6.6, 8)
```

```{r}
vec = function(x, n){
  pow = 0:n
  val = sum(x^pow)
  
  return (val)
}
```

```{r}
vec(0.3, 55)
vec(6.6, 8)
```
