---
title: "Lab 6"
output: html_notebook
---

Task 1a

```{r}
data <- read.csv('ufc.csv')
data
```

```{r}
three_tall <- data[order(data$height.m, decreasing = TRUE), 'species'][1:3]
three_tall
```

```{r}
five_fat <- data[order(data$dbh.cm, decreasing = TRUE), 'species'][1:5]
five_fat
```

Task 1b

```{r}
mean_diam_species <- aggregate(data$dbh.cm, list(data$species), mean)
mean_diam_species
```

Task 1c

```{r}
third_quartile <- function(x) quantile(x, probs = 0.75)
third_quartile_diameters <- aggregate(data$dbh.cm, list(data$species), third_quartile)

names(third_quartile_diameters) <- c('species', 'third_quartile diam')
third_quartile_diameters
```

```{r}
largest_third_quartile_species <- third_quartile_diameters[order(third_quartile_diameters$`third_quartile diam`, decreasing = TRUE), "species"][1:2]

largest_third_quartile_species
```

Task 1d

```{r}
names(mean_diam_species) <- c('species', 'mean_diameter')
mean_diam_species
```

```{r}
fattest <- mean_diam_species[order(mean_diam_species$mean_diameter, decreasing = TRUE), 'species'][1]
fattest
```

```{r}
subset <- data[data$species == fattest, ]
subset
```

```{r}
tallest_identity <- subset[order(subset$height.m, decreasing = TRUE), ][1,]
tallest_identity
```

Task 2a

```{r}
mammals <- read.csv("sleep.csv")
mammals
```

```{r}
plot(mammals$BodyWt, mammals$BrainWt, 
     xlab = "Body Weight (kg)", ylab = "Brain Weight (g)",
     main = "Brain Weight vs. Body Weight", pch = 19)
```

```{r}
model <- lm(BrainWt ~ BodyWt, data = mammals)
summary(model)
```

```{r}
# Plot the diagnostics plots
par(mfrow = c(2, 2)) # Set up a 2x2 grid for plots
plot(model) # Residuals vs Fitted, Normal Q-Q, Scale-Location, Residuals vs Leverage

# Reset the plot layout
par(mfrow = c(1, 1))
```

Task 2b

```{r}
mammals$BodyWt <- log(mammals$BodyWt)
mammals$BrainWt <- log(mammals$BrainWt)
```

```{r}
model2 <- lm(BrainWt ~ BodyWt, data = mammals)
summary(model)
```

```{r}
plot(mammals$BodyWt, mammals$BrainWt, 
     xlab = "Log Body Weight (kg)", ylab = "Log Brain Weight (g)",
     main = "Brain Weight vs. Body Weight", pch = 19)

abline(model2$coefficients, col = "blue", lwd = 2)
```

```{r}
# Plot the diagnostics plots
par(mfrow = c(2, 2)) # Set up a 2x2 grid for plots
plot(model2) # Residuals vs Fitted, Normal Q-Q, Scale-Location, Residuals vs Leverage

# Reset the plot layout
par(mfrow = c(1, 1))
```

Task 2c

```{r}
predict(model2, list(BodyWt = log(50)), interval = "confidence", level = 0.95)
```

```{r}
predict(model2, list(BodyWt = log(50)), interval = "prediction", level = 0.95)
```
